[package]
name = "server"
version = "0.1.0"
authors = ["Sam Jeston <sam.jeston@gmail.com>"]

[dependencies]
ws = "0.7.9"
env_logger = "0.5.13"
lazy_static = "1.1.0"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
